// <auto-generated />
using Jarasoft.Sicotyc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jarasoft.Sicotyc.Infrastructure.Migrations
{
    [DbContext(typeof(SicotycDbContext))]
    [Migration("20260920235209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jarasoft.Sicotyc.Domain.Entities.Ubigeo", b =>
                {
                    b.Property<string>("IdDist")
                        .HasColumnType("char(6)")
                        .HasColumnName("IDDIST");

                    b.Property<int>("CodigoRegionNatural")
                        .HasColumnType("int")
                        .HasColumnName("COD_REG_NAT");

                    b.Property<string>("NombreCapital")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOM_CAPITAL");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOMBDEP");

                    b.Property<string>("NombreDistrito")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOMBDIST");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOMBPROV");

                    b.Property<string>("RegionNatural")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REGION_NATURAL");

                    b.HasKey("IdDist");

                    b.ToTable("Ubigeos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
